######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 30 15:54:59 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += age.cpp
